# Generated by Django 3.2.8 on 2021-11-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABookAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phonenumber',
            field=models.TextField(),
        ),
    ]
