# Generated by Django 3.2.8 on 2022-05-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABookAPP', '0002_alter_address_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='AddressClass',
        ),
    ]
